[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx-stdout.log
stderr_logfile=/var/log/nginx-stderr.log

[program:node]
command=node /app/backend/index.js
autostart=true
autorestart=true
stdout_logfile=/var/log/node-stdout.log
stderr_logfile=/var/log/node-stderr.log